### PR TITLE
Related Resources

### LINKED ISSUE #7: Fetching a related resource
I didn't see an ability to fetch a [related resource](https://jsonapi.org/format/#fetching-resources)

In the spec's example I'm trying to do
```
GET /articles/1/author HTTP/1.1
Accept: application/vnd.api+json
```

I tried to hack in a way on the `BaseResource` to add the route automatically
I could not find a way to look at the `schema` and determine the fields that were of `JSONAPIRelationship`. Maybe I am missing something. Is this possible?

### PR DESCRIPTION
**Pull request by vladmunteanu**
Related Resources functionality:
- to support fetching related data, one will need to implement `get_related`, calling `serialize_related` to serialize the data.
- to expose related links when rendering a relationship, one will need to set `related_resource`, `related_route` and `related_route_kwargs` when creating a `JSONAPIRelationship` object.

** (breaks up resources tests as well)
*** adds `request_context` on `BaseResource`, to host the active request context. For now a simple `dict` should do.

Fixes #7

### CODE REVIEW

**Comment by vladmunteanu** [comment]
So this proved to be rather difficult and I'm still not sure whether this is the way to go ... 

My initial idea was to add a `get_related` method, which receives the parent object id and the name of the related resource (`'author'` for something like `/articles/1/author`). A typical `get_related` implementation would fetch the parent object, then call something like `serialize_related` with the parent object, and the name of the relationship (which it got as argument).
`serialize_related` would handle instantiating the correct schema and serializing the related resource.

It could also handle stuff like top level links better i think.

**Comment by khornberg** [comment]
>One thing I'm not sure of, is what is the specs' stance on fetching a specific object in a nested level, for example /articles/1/comments/12

The spec doesn't give examples of this. I can see the usefulness of the ability to if it is possible. Seems like an option at this point

**Comment by vladmunteanu** [comment]
So, with each day that passes, and your comments @pOctav and @khornberg, I think I'm more towards the idea I commented above, for a few reasons:

- the `serialize_related` could take care of things such as the top level links object. If we use this PR's implementation instead, the generated links will be those from the relateted resource (in our example: /authors/1 instead of /articles/1/authors )

- serializing many would also be controlled by passing `many=True` to `serialize_related`

- `handle_get_related` will get a lot more simple, since we could rely on `handle_request` to call the handler (`get_related`) and catch exceptions.

The only downside I can think of right now:
- it would make resources implement the actual fetching of related resources inside `get_related` which would mean the resource would likely to have to know about the related model too. 

But thinking more about this, if you actually have a relationship with another resource, chances are pretty high that you are going to import the referenced model and use it when populating the relationship anyway.

What do you think about this approach?



@pOctav: I'd rather not subclass Request if possible, and keep using the one from Starlette. Also, using marshmallow Schema fields is pretty uggly ... I wanted to use the relationship object when specifying a BaseRelationshipResource subclass, instead of the relationship name as it is now. I didn't like that you can't simply do that because marshmallow doesn't expose the fields publicly on a schema (you can access them as _declared_fields tho, which I later exposed as JSONAPISchema.get_fields()). But doing so would still look like this:  `some_rel = SomeSchema.get_fields()['rel']`.
I think the approach I was describing above would offer the desired functionality without having to subclass Request or store the relationship object in `_related`.

**Comment by vladmunteanu** [comment]
I'm still thinking about `links` and what to do with them, so I've included some tests for now to make things clear.
Not sure whether we're forced to follow the example in the spec regarding the generated `links` in the returned payload.

**Comment by vladmunteanu** [comment]
I think I'm reaching the final steps with this one.

The following are now supported:
/articles/1/author
/articles/1/comments
/articles/1/comments/2

**Comment by vladmunteanu** [comment]
To generate the correct links, serialize_related signature has changed to:
```async def serialize_related(self, data: Any, id: Any, relationship: str, many=False, *args, **kwargs) -> dict:```

**Comment by khornberg** [comment]
I think it provides a good foundation

**Pull request merged**
